# BÀI 1: LÀM QUEN VỚI PYTORCH

## Bài 1:Tạo Tensor cơ bản

In [2]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


### Yêu cầu: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.
Kích thước: 2 × 3, gồm 2 hàng và 3 cột.<br>
Số chiều: 2 chiều.<br>
Kiểu dữ liệu: torch.int32.

## Bài 2. Tạo các Tensor thường dùng

In [4]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)
f = torch.full((5, 5), 10)
print(f)

tensor([[0.4646, 0.7776, 0.7698, 0.0804],
        [0.4663, 0.3569, 0.4008, 0.8806],
        [0.2503, 0.4183, 0.7206, 0.5393]])
tensor([[-0.6992,  0.2806,  2.4374,  1.8016],
        [ 0.5474, -0.4238, -0.2797,  1.1549],
        [-0.8007,  1.1694,  0.8363,  0.1120]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


### Yêu cầu 1: Nhận xét sự khác nhau giữa torch.rand() và torch.randn()
torch.rand() tạo tensor gồm các giá trị ngẫu nhiên theo phân phối đều trong khoảng từ 0 đến nhỏ hơn 1. Trong khi đó, torch.randn() tạo tensor gồm các giá trị ngẫu nhiên theo phân phối chuẩn, có giá trị trung bình bằng 0 và độ lệch chuẩn bằng 1.
### Yêu cầu 2: Tạo Tensor 5 × 5 chứa toàn giá trị 10:
Sử dụng hàm torch.full((5, 5), 10) để tạo Tensor có kích thước 5 × 5 và tất cả các phần tử đều có giá trị bằng 10.

## Bài 3. Kiểm tra thông tin Tensor

In [5]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


### Yêu cầu: Giải thích ý nghĩa của torch.Size([2, 3, 4])
torch.Size([2, 3, 4]) cho biết Tensor có 3 chiều, với kích thước lần lượt là:<br>
Chiều 1: 2 phần tử.<br>
Chiều 2: 3 phần tử.<br>
Chiều 3: 4 phần tử.<br>
Như vậy, Tensor có tổng cộng 2 × 3 × 4 = 24 phần tử<br>

## Bài 4. Slicing và Indexing

In [6]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 1.2395, -0.3580,  0.7822,  0.3068,  1.1768],
         [-0.6792,  2.2361, -1.3449, -0.3218,  1.2693],
         [ 0.0337, -0.0615, -1.8509, -1.1639, -1.0201],
         [-0.4643,  0.8787,  0.0765,  0.6311,  0.2850]],

        [[-0.1037, -0.5285, -1.0895, -3.4701,  0.7165],
         [-0.6053,  0.6450, -1.8788,  1.3917, -0.5531],
         [ 1.0791, -1.2006, -0.3736,  0.9479,  0.9313],
         [ 0.8593, -0.4849,  0.0984, -1.4551,  0.6708]],

        [[ 1.5508,  1.3941,  0.3384, -0.3790, -1.6853],
         [ 0.3662, -0.3507,  0.6225, -1.3221, -1.7745],
         [ 0.6837, -2.1949, -0.4769,  0.4191, -0.5318],
         [ 0.7464, -0.6526,  0.2987, -0.1429,  0.2160]]])

Tensor a[1]:
tensor([[-0.1037, -0.5285, -1.0895, -3.4701,  0.7165],
        [-0.6053,  0.6450, -1.8788,  1.3917, -0.5531],
        [ 1.0791, -1.2006, -0.3736,  0.9479,  0.9313],
        [ 0.8593, -0.4849,  0.0984, -1.4551,  0.6708]])

Tensor a[1:, 2:4]:
tensor([[[ 1.0791, -1.2006, -0.3736,  0.9479,  0.9

### Yêu cầu 1: Cho biết shape của a[1] và a[1:, 2:4].
### Yêu cầu 2: Thử lấy hai phần tử cuối cùng trên chiều thứ ba.
a[1] có shape (4, 5) vì lấy phần tử thứ 2 trên chiều đầu tiên của Tensor a có shape (3, 4, 5)<br>
a[1:, 2:4] có shape (2, 2, 5) vì lấy từ phần tử thứ 2 đến hết ở chiều thứ nhất và lấy vị trí thứ 3 đến thứ 4 ở chiều thứ hai<br>
Để lấy hai phần tử cuối cùng trên chiều thứ ba, sử dụng a[:, :, -2:]. Tensor kết quả có shape (3, 4, 2)<br>


### Bài 5. Reshape và Flatten

In [7]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 0.6962,  0.2458,  0.1403, -2.2186],
        [-0.3513,  2.0601,  1.9695,  0.8506],
        [ 0.9073, -1.5725,  0.2180,  0.3431]])

Flatten:
tensor([ 0.6962,  0.2458,  0.1403, -2.2186, -0.3513,  2.0601,  1.9695,  0.8506,
         0.9073, -1.5725,  0.2180,  0.3431])

Reshape to 3 x 2 x 2:
tensor([[[ 0.6962,  0.2458],
         [ 0.1403, -2.2186]],

        [[-0.3513,  2.0601],
         [ 1.9695,  0.8506]],

        [[ 0.9073, -1.5725],
         [ 0.2180,  0.3431]]])


### Yêu cầu:

#### Kiểm tra số phần tử trước và sau khi reshape.<br>
#### Thử reshape Tensor thành kích thước 2 × 6.<br>
Tensor a có shape (3, 4) nên có tổng cộng 3 × 4 = 12 phần tử<br>
Sau khi reshape(3, 2, 2), Tensor có 3 × 2 × 2 = 12 phần tử. Như vậy, số phần tử không thay đổi sau khi reshape<br>
Có thể reshape Tensor thành kích thước 2 × 6 bằng lệnh a.reshape(2, 6)<br>
Tensor sau khi reshape thành (2, 6) vẫn có 12 phần tử<br>

## Bài 6. Phép toán và nhân ma trận

In [8]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 1.4262, -0.4089, -1.6028],
        [ 0.2217,  1.4808,  1.5664]])
b:
tensor([[ 0.3054, -1.1647,  0.3004],
        [ 1.3772, -1.8957, -0.0594]])

a + b:
tensor([[ 1.7316, -1.5736, -1.3024],
        [ 1.5989, -0.4149,  1.5070]])

a / b:
tensor([[  4.6692,   0.3511,  -5.3353],
        [  0.1610,  -0.7811, -26.3603]])

a^2:
tensor([[2.0341, 0.1672, 2.5690],
        [0.0491, 2.1927, 2.4536]])

Matrix multiplication:
tensor([[ 0.4304,  2.8346],
        [-1.1864, -2.5949]])


### Yêu cầu:
### Phân biệt phép toán a * b với a @ b.T.
### Cho biết shape của kết quả a @ b.T.
a * b là phép nhân từng phần tử (element-wise multiplication). Hai Tensor a và b phải có shape tương thích. Trong bài này, cả hai đều có shape (2, 3), nên kết quả có shape (2, 3)<br>
a @ b.T là phép nhân ma trận (matrix multiplication). Tensor b có shape (2, 3) nên b.T có shape (3, 2). Do đó, a có shape (2, 3) nhân với b.T có shape (3, 2) sẽ cho kết quả có shape (2, 2)<br>

## Bài 7. Các hàm thống kê trên Tensor

In [9]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 1.3726, -0.9335, -1.0423,  0.7827],
        [-0.1404, -1.8490,  0.4176,  1.2622],
        [-0.2572,  0.2302,  0.8062, -1.1850]])

Mean:
tensor([ 0.3250, -0.8507,  0.0605,  0.2866])

Standard deviation:
tensor([0.9091, 1.0421, 0.9746, 1.2968])

Cumulative sum:
tensor([[ 1.3726, -0.9335, -1.0423,  0.7827],
        [ 1.2321, -2.7825, -0.6248,  2.0449],
        [ 0.9749, -2.5522,  0.1814,  0.8599]])


In [11]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=1))
print("\nStandard deviation:")
print(torch.std(a, dim=1))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 1.2694, -1.3822,  0.5393, -0.2051],
        [ 1.0843,  0.8414, -1.1747, -0.0433],
        [-0.9713,  0.8284, -0.3522,  0.2711]])

Mean:
tensor([ 0.0554,  0.1769, -0.0560])

Standard deviation:
tensor([1.1317, 1.0231, 0.7777])

Cumulative sum:
tensor([[ 1.2694, -0.1128,  0.4265,  0.2214],
        [ 1.0843,  1.9257,  0.7510,  0.7077],
        [-0.9713, -0.1429, -0.4951, -0.2240]])


### Yêu cầu: Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.
dim=0: tính toán theo cột<br>
dim=1: tính toán theo hàng<br>
mean và std cho kết quả có shape lần lượt là (4,) và (3,)<br>
cumsum vẫn có shape (3, 4) nhưng thứ tự cộng dồn thay đổi<br>

## Bài 8. Autograd cơ bản

In [12]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


### Yêu cầu:
#### Tính thủ công đạo hàm của y = x2 tại x = 3.6 và so sánh với x.grad.
#### Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.
Với y = x²:<br>
y' = 2x<br>
Tại x = 3.6: y' = 2 × 3.6 = 7.2<br>
x.grad = 7.2 → khớp với kết quả tính thủ công<br>
Với y = 3x² + 2x + 1:<br>
y' = 6x + 2<br>
Tại x = 3.6: y' = 6 × 3.6 + 2 = 23.6<br>
Kết quả x.grad sẽ là 23.6<br>

## Bài 9. Gradient Descent tìm hệ số đa thức

In [14]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
   optimizer.zero_grad()
   y_pred = x @ w
   mse = torch.mean(torch.square(y - y_pred))
   mse.backward()
   optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 0.3098],
        [-0.3627],
        [-1.0228]], requires_grad=True)
Learned coefficients:
tensor([[1.0378],
        [1.8852],
        [1.3438]], requires_grad=True)


### Yêu cầu:
#### So sánh ba hệ số học được với [1, 2, 3].
#### Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().
Ba hệ số học được sẽ xấp xỉ [1, 2, 3]. Sai số nhỏ có thể xuất hiện do dữ liệu ngẫu nhiên và quá trình tối ưu<br>
optimizer.zero_grad(): Xóa gradient của lần lặp trước để tránh gradient bị cộng dồn<br>
mse.backward(): Tính gradient của hàm mất mát mse đối với các hệ số w<br>
optimizer.step(): Cập nhật các hệ số w dựa trên gradient để giảm giá trị mse

## Bài 10. Giải hệ phương trình bằng Autograd

In [16]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
   y1 = A + B - 9
   y2 = C - D - 1
   y3 = A + C - 8
   y4 = B - D - 2
sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
optimizer.zero_grad()
sqerr.backward()
optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(0.4743, requires_grad=True)
B = tensor(0.8901, requires_grad=True)
C = tensor(0.1134, requires_grad=True)
D = tensor(0.4050, requires_grad=True)


### Yêu cầu:
#### Kiểm tra nghiệm thu được với bốn phương trình.
#### Nhận xét vì sao bài toán có thể có nhiều nghiệm.
Nghiệm thu được cần thỏa mãn cả bốn phương trình:<br>
A + B = 9<br>
C - D = 1<br>
A + C = 8<br>
B - D = 2<br>
Bài toán có nhiều nghiệm vì bốn phương trình không độc lập hoàn toàn. Ta có thể chọn một giá trị tự do, sau đó xác định các giá trị còn lại.

## Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:

In [2]:
import torch
X = torch.arange(1, 25)

print("X =", X)

X1 = X.reshape(4, 6)
X2 = X.reshape(2, 12)
X3 = X.reshape(2, 3, 4)

print("\nX reshape 4x6:")
print(X1)

print("\nX reshape 2x12:")
print(X2)

print("\nX reshape 2x3x4:")
print(X3)

A = torch.tensor([
    [1., 2., 3., 4.],
    [5., 6., 7., 8.],
    [9., 10., 11., 12.]
])

B = torch.tensor([
    [2., 4., 6., 8.],
    [1., 2., 3., 4.],
    [2., 5., 10., 20.]
])

print("\nA + B:")
print(A + B)

print("\nA * B:")
print(A * B)

print("\nA / B:")
print(A / B)

# Trung bình theo cột
mean_col = torch.mean(A, dim=0)
print("\nTrung bình theo cột của A:")
print(mean_col)

# Độ lệch chuẩn theo cột
std_col = torch.std(A, dim=0)
print("\nĐộ lệch chuẩn theo cột của A:")
print(std_col)

x = torch.tensor(2.0, requires_grad=True)

y = 2*x**2 + 5*x + 3

y.backward()

print("\nGiá trị y tại x = 2:", y.item())
print("dy/dx bằng autograd:", x.grad.item())
print("dy/dx tính thủ công:", 4*2 + 5)

x_train = torch.linspace(-5, 5, 100)

y_train = 2*x_train**2 - 3*x_train + 5

a = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
c = torch.randn(1, requires_grad=True)

learning_rate = 0.001

for epoch in range(10000):

    # Dự đoán
    y_pred = a*x_train**2 + b*x_train + c

    # Mean Squared Error
    loss = torch.mean((y_pred - y_train)**2)

    # Tính gradient
    loss.backward()

    # Cập nhật hệ số
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        c -= learning_rate * c.grad

    # Xóa gradient
    a.grad.zero_()
    b.grad.zero_()
    c.grad.zero_()

print("\nKết quả huấn luyện:")
print("a =", a.item())
print("b =", b.item())
print("c =", c.item())

print("\nPhương trình tìm được:")
print(f"y = {a.item():.4f}x^2 + {b.item():.4f}x + {c.item():.4f}")

X = tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

X reshape 4x6:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])

X reshape 2x12:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

X reshape 2x3x4:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

A + B:
tensor([[ 3.,  6.,  9., 12.],
        [ 6.,  8., 10., 12.],
        [11., 15., 21., 32.]])

A * B:
tensor([[  2.,   8.,  18.,  32.],
        [  5.,  12.,  21.,  32.],
        [ 18.,  50., 110., 240.]])

A / B:
tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [5.0000, 3.0000, 2.3333, 2.0000],
        [4.5000, 2.0000, 1.1000, 0.6000]])

Trung bình theo cột của A:
tensor([5., 6., 7., 8.])

Độ lệch chuẩn